#!/bin/bash
if pgrep mapcrafter > /dev/null; then
  echo "Mapcrafter already running?"
  exit 1
fi

cd "$( dirname "$0" )"
rsync -aL --delete ../world .
/usr/local/bin/mapcrafter -c render.conf -j 7
~/go/bin/playerMarkers -c player-markers-config.json


keychain id_rsa
. ~/.keychain/`uname -n`-sh
rsync -acvz --files-from=rsync-include -e ssh output/current/ nfsipm:/home/public/maps/current/embed
